name: Comment
concurrency: ${{ github.workflow }}

on:
 schedule:
  - cron: '0 10 * * *'
 workflow_dispatch:


jobs:
  comment:
    runs-on: ubuntu-latest
    timeout-minutes: 1000
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.3
      - name: Install package
        run : |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -e .
          python3 -m playwright install chromium
      - name: Run Bot
        run: python3 hottakes/bot/driver.py
        env: 
          PINKBIKE_USER: ${{ secrets.PINKBIKE_USER }}
          PINKBIKE_PASS: ${{ secrets.PINKBIKE_PASS }}
          AZURE_STORAGE_CONN_STR: ${{ secrets.AZURE_STORAGE_CONN_STR }}
